### ISSUE TITLE
在Android 12上捕捉屏幕截图会崩溃

### ISSUE THREAD

**Issue by HinataKato** [ekibun/Stitch#2]
Arrow OS 12.1 红米 K40 应用v1.0.16

```
Generated by AppErrorsTracking
Project Url: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Redmi
[Device Model]: M2012K11AC
[Display]: SQ3A.220705.003
[Android Version]: 12
[API Version]: 32
[Package Name]: soko.ekibun.stitch
[Error Type]: Jvm
[Crash Time]: Aug 5, 2022 08:42:48
[Stack Trace]:
java.lang.RuntimeException: Unable to create service soko.ekibun.stitch.CaptureService: java.lang.IllegalArgumentException: soko.ekibun.stitch: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4567)
	at android.app.ActivityThread.access$1700(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.IllegalArgumentException: soko.ekibun.stitch: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:724)
	at android.app.PendingIntent.getService(PendingIntent.java:686)
	at y.r$a.f(:5)
	at e.g.getValue(Unknown Source:20)
	at y.r.a(Unknown Source:2)
	at y.r.<init>(Unknown Source:36)
	at soko.ekibun.stitch.CaptureService$b.f(:1)
	at e.g.getValue(Unknown Source:20)
	at soko.ekibun.stitch.CaptureService.onCreate(:3)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4554)
	... 9 more
```

**Comment by ekibun** [comment]
新版本应该没有问题了
